name: Deploy POC application on Azure Web App x Docker Container

on:
    push:
        branches:
            - 1794-Migrage_Static_Web_App_To_Web_App_And_Docker
            - main
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                required: true
                default: 'staging'
                type: choice
                options:
                    - staging
                    - production
            tina_branch:
                description: 'Tina branch to use'
                required: false
                default: ''
                type: string

concurrency:
    group: ${{ github.ref_name }}-deployment
    cancel-in-progress: true

permissions:
    id-token: write
    contents: read

jobs:
    build:
        name: Build and Push Container
        uses: ./.github/workflows/build-artifacts.yml
        with:
            tag: ${{ github.event.inputs.environment || 'staging' }}
            registry_name: 'sswrulestinastaging'
            image_name: 'ssw-rules-tina-staging-nextjs'
            tina_branch: ${{ github.event.inputs.tina_branch || secrets.NEXT_PUBLIC_TINA_BRANCH }}
        secrets:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
            NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
            NEXT_PUBLIC_TINA_BRANCH: ${{ secrets.NEXT_PUBLIC_TINA_BRANCH }}
            TOKEN: ${{ secrets.POC_PAT_GILLES }}
            NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
            NEXT_PUBLIC_ALGOLIA_ADMIN_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_ADMIN_KEY }}
            NEXT_PUBLIC_ALGOLIA_INDEX_NAME: ${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}
            NEXT_PUBLIC_ALGOLIA_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_API_KEY }}

    deploy:
        name: Deploy to Azure Web App
        runs-on: ubuntu-latest
        needs: build
        environment: staging
        steps:
            - name: Azure CLI - Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                  app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
                  images: ${{ needs.build.outputs.image_tag }}

            - name: Verify deployment
              run: |
                  echo "Application deployed successfully!"
                  echo "Image: ${{ needs.build.outputs.image_tag }}"
                  echo "App URL: https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net"