name: Deploy Next.js site to Azure Static Web Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_ALGOLIA_APP_ID:    ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
      NEXT_PUBLIC_ALGOLIA_ADMIN_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_ADMIN_KEY }}
      NEXT_PUBLIC_ALGOLIA_INDEX_NAME: ${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}
      NEXT_PUBLIC_ALGOLIA_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      # 1 – Node (no pnpm cache yet)
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc      # "22" in your repo

      # 2 – Install pnpm and add it to PATH (+ cache)
      - uses: pnpm/action-setup@v4
        with:
          version: 10.10.0               # keep in sync with packageManager
          run_install: true             # we control install step

      # 3 – Install dependencies
      - run: pnpm install --frozen-lockfile

      # 4 – Algolia sync
      - run: pnpm exec node scripts/update_algolia_index.js

      - name: Checkout Content repo
        uses: actions/checkout@v4
        with:
          repository: SSWConsulting/SSW.Rules.Content
          ref: tina/Content_Azure_Deployment-Categories
          path: content-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy test.json
        run: |
          cp content-repo/scripts/tina-migration/rule-category-mapping.json ./rule-category-mapping.json

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add rule-category-mapping.json
          git commit -m "Update rule-category-mapping.json from Content repo" || echo "No changes"
          git push

      # 5 – Static build for Azure Static Web Apps
      - run: pnpm build
        env:
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
          NEXT_PUBLIC_TINA_BRANCH:    content_deployment
          TINA_TOKEN:                 ${{ secrets.TINA_TOKEN }}

      # 6 – Copy staticwebapp.config.json to out/
      - run: cp staticwebapp.config.json out/

      # 7 - Upload to Azure Static Web Apps
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          skip_app_build: true
          skip_api_build: true
          app_location: out
