name: "test"

on: 
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  test_login:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI - Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
